/**
 * Build-time product-image optimizer (runs locally, never in the browser).
 *
 * Product photos in /img are the original high-res source files — some are
 * 2560x2560 PNGs at ~4 MB, rendered into 163px grid slots. This script emits
 * responsive WebP variants (400w + 800w) next to each source so the storefront
 * can serve a right-sized image via <picture srcset>. Originals are kept
 * untouched as the fallback for the <img> element.
 *
 * sharp is a devDependency: it is used here at authoring time and the generated
 * .webp files are committed. Vercel/CI just serves the static output — sharp is
 * never required in the deploy pipeline and never enters the client bundle.
 *
 * Idempotent: skips a variant whose file already exists and is newer than its
 * source, so re-runs after adding a few products are fast.
 */
import { readdirSync, statSync, existsSync, writeFileSync } from 'node:fs';
import { join, parse } from 'node:path';
import sharp from 'sharp';

const IMG_DIR = 'img';
const WIDTHS = [400, 800];
const QUALITY = 80;
const SRC_RE = /\.(png|jpe?g)$/i;

const files = readdirSync(IMG_DIR).filter((f) => SRC_RE.test(f) && !/-\d+\.webp$/.test(f));

let made = 0, skipped = 0, savedSrc = 0, savedOut = 0;
const rows = [];
const optimized = [];   // basenames that have a full set of WebP variants

for (const file of files) {
  const src = join(IMG_DIR, file);
  const { name } = parse(file);
  const srcStat = statSync(src);
  let meta;
  try { meta = await sharp(src).metadata(); } catch { continue; }
  optimized.push(name);

  for (const w of WIDTHS) {
    // Never upscale: if the source is narrower than the target width, cap at source.
    const targetW = Math.min(w, meta.width || w);
    const out = join(IMG_DIR, `${name}-${w}.webp`);
    if (existsSync(out) && statSync(out).mtimeMs >= srcStat.mtimeMs) { skipped++; continue; }
    await sharp(src)
      .resize({ width: targetW, withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 5 })
      .toFile(out);
    made++;
    savedOut += statSync(out).size;
  }
  savedSrc += srcStat.size;
  if (srcStat.size > 500 * 1024) {
    const w800 = join(IMG_DIR, `${name}-800.webp`);
    rows.push(`  ${file.padEnd(16)} ${(srcStat.size / 1024 / 1024).toFixed(2)}MB -> 800w ${(statSync(w800).size / 1024).toFixed(0)}KB`);
  }
}

// Manifest the app imports so it only emits <source srcset> for images that
// actually have variants — a product added before the next optimizer run
// simply falls back to its original <img>, never a broken picture source.
optimized.sort();
writeFileSync(
  'src/data/optimizedImages.js',
  '// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n' +
  '// Basenames under /img that have responsive WebP variants (-400.webp, -800.webp).\n' +
  `export const OPTIMIZED_IMAGES = new Set(${JSON.stringify(optimized)});\n` +
  'export const OPTIMIZED_WIDTHS = [400, 800];\n'
);

console.log(`\nGenerated ${made} WebP variants (${skipped} up to date) from ${files.length} sources.`);
console.log(`Wrote manifest: src/data/optimizedImages.js (${optimized.length} images).`);
if (rows.length) console.log('Largest sources:\n' + rows.slice(0, 12).join('\n'));
console.log(`\nTotal WebP output across all variants: ${(savedOut / 1024 / 1024).toFixed(1)} MB`);
